[tool.ruff]
line-length = 120

[tool.ruff.lint]
# Enable Pyflakes (`F`), pycodestyle (`E`, `W`), isort (`I`), and Bandit (`S`).
select = ["F", "E", "W", "I", "S"]
ignore = []

[tool.ruff.lint.per-file-ignores]
# Ignore assert usage (S101) in tests
"backend/tests/*" = ["S101"]
